### ISSUE TITLE
What is a stablecoin? [blog post]

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-heroes#13]
## Suggestion

A written post about what are stablecoins, why are they innovative, the market history, and/or anything else interesting.

## Related

This would likely be a "community featured" post on the [Hedera Learning Center](https://www.hedera.com/learning/what-is-hedera-hashgraph).

**Comment by harivamsi9** [comment]
Hey @Cooper-Kunz, are you still for the blog post on "What is a stablecoin?"

**Comment by bmgentile** [comment]
Hi @harivamsi9 we have actually created this already, here: https://www.hedera.com/learning/what-is-a-stablecoin/

Thank you for checking! I'll close this out.
