### ISSUE TITLE
Getting started with Hedera Token Service tutorial [$1000 USD of HBAR]

### ISSUE THREAD

**Issue by gakz** [hashgraph/hedera-heroes#17]
## Suggestion

Getting started with Hedera Token Service tutorial. With HTS available on the previewnet for the first time, this would be a comfortable introduction to HTS and allow for developers to mint, view, and transfer a token within an example application. Ideally but not required to be in JavaScript, all code would be open-sourced.

## Related

Similar tutorial example - https://hedera.com/blog/build-your-first-hcs-powered-web-app

**Comment by christianholman** [comment]
I'm going to start working on a little project ~token toolbox~ showcasing managing tokens :)

**Comment by christianholman** [comment]
> I'm going to start working on a little project ~token toolbox~ showcasing managing tokens :)

Got stuck in some other things. Luckily the HTS-token demo just released by Hedera was exactly what I was trying to make. Don't feel blocked if trying to go for something similar.

**Comment by bugbytesinc** [comment]
Updated the **Hashgraph API Portal** to include all **HTS** functions.  

Open Source Preview Branch located at: https://github.com/bugbytesinc/Hashgraph-Portal/tree/network-version-9

Preview Deployment at:  https://previewnet.azurewebsites.net/createtoken

This is a reference implementation using .NET SDK 0.7.0 RC1

Once TESTNET enables HTS the API Portal site and .NET SDK 0.7.0 will produce releases.

**Comment by gakz** [comment]
Thanks, @bugbytesinc, this is great. Is it ok for us to include this alongside your blog post upon testnet release on Hedera.com?

**Comment by bugbytesinc** [comment]
Yep

**Comment by batuhantastekin** [comment]
Can we do in Turkish?

**Comment by bmgentile** [comment]
@gakz could we close this one out?

**Comment by csor-dev** [comment]
@bmgentile Is this tutorial completed?

**Comment by csor-dev** [comment]
If it's not I would like to do it

**Comment by bmgentile** [comment]
It has been completed, sorry @csor-dev
