### ISSUE TITLE
Build a web app to monitor account transactions 

### ISSUE THREAD

**Issue by gakz** [hashgraph/hedera-heroes#5]
We'd like to track the funds sent from the Hedera Heroes account to other accounts. This post would go through the process of building a simple, open source web app that can view the amount of funds sent from the Hedera Heroes account to other accounts. 

This could:

- Use the Dragonglass API - https://dragonglass.me/

- Rank the accounts that have received the largest amount of hbar from Hedera Heroes

**Comment by christianholman** [comment]
I'd love to take this one on if it's not already being worked on.

**Comment by christianholman** [comment]
Should it be written in a framework, or should it just use vanilla JS + HTML + CSS? In the case of being written in a framework, which would be preferable? 
![screenshot_20200421_215646](https://user-images.githubusercontent.com/17482674/79908235-26504680-841b-11ea-99c9-a36da94ed8f7.png)

**Comment by gakz** [comment]
Hey @christianholman, that'd be great. Vanilla or a framework would work, whichever your preference. If framework, the community seems to be encouraging React or Vue if possible.

**Comment by christianholman** [comment]
What is the Hedera Heroes account ID?

**Comment by gakz** [comment]
We've changed the process so it won't be exclusive to Heroes, but you can get started with 0.0.76. Looking forward to the demo and blog post!

**Comment by christianholman** [comment]
Demo & draft:
https://github.com/christianholman/hedera-hunt/
https://github.com/christianholman/hedera-hunt/blob/master/post.md

**Comment by Cooper-Kunz** [comment]
This was completed awhile ago, so closing the issue. Thanks @christianholman!
